# Project-wide Gradle settings.
android.useAndroidX=true
# Jetifier is only needed if you use old support libraries. 
# It is deprecated in newer AGP versions.
android.enableJetifier=true

# Optimization settings
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=false
org.gradle.vfs.watch=false
org.gradle.daemon=false
android.defaults.buildfeatures.resvalues=true
android.sdk.defaultTargetSdkToCompileSdkIfUnset=false
android.enableAppCompileTimeRClass=false
android.usesSdkInManifest.disallowed=false
android.uniquePackageNames=false
android.dependency.useConstraints=true
android.r8.strictFullModeForKeepRules=false
android.r8.optimizedResourceShrinking=false
android.builtInKotlin=false
android.newDsl=false
